import React from "react";
import Fade from "react-reveal/Fade";
import Lottie from "react-lottie";
import Anim7 from "../../assets/animaton/drawkit-grape-animation-8-LOOP.json";
import {BrowserRouter as Router, Switch, Route, Link} from "react-router-dom";
import "./Ourproject.css";

const OurProject = () => {
	const defaultOptions = {
		loop: true,
		autoplay: true,
		animationData: Anim7,
	};
	const source =
		"https://riwayat-file-covid-19-dki-jakarta-jakartagis.hub.arcgis.com/";
	return (
		<section id="ourproject">
			<div className="container">
				<div className="row board">
					<h2 className="center-align">Our Project</h2>
					<div className="row">
						<div className="col s12 m6 l6 right">
							<div className="img-responsive">
								<Fade right>
									<Lottie options={defaultOptions} />
								</Fade>
							</div>
						</div>
						<div className="col s12 m6 l6">
							<Fade left>
								<p>
									This project purpose is predicts when the
									peak of the spread of COVID-19 in DKI
									Jakarta. The data we obtained came from{" "}
									&nbsp;
									<a href={source} target="_blank">
										COVID 19 DKI Jakarta
									</a>
									&nbsp; which began on March 25, 2020 until
									June 10, 2020. Furthermore, the data we have
									taken cleansing can be done such can be done
									as column selection that will be used to get
									COVID-19 historical data in all
									Administration Cities in Jakarta every day.
								</p>
								<p>
									{" "}
									The model used in the COVID-19 disease
									spread model in Jakarta is the SEIRD model.
									This model was chosen because it is in
									accordance with the spread of COVID-19
									disease itself. The SEIRD model chosen is
									divided into six compartments: Susceptible,
									Exposed, Infected, Recovered, Dead. And we
									also do not forget to determine some
									assumptions for the model that we use.
								</p>
								<p>
									{" "}
									After the data goes through the ETL process
									and the model is ready, we finally reach the
									final stage, which is to make a dashboard of
									the data generated by the model and provide
									it in the form of the website that you see
									now.
								</p>
								<Link
									to={"/project-detail"}
									className="btn center"
								>
									See Details!
								</Link>
							</Fade>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
};

export default OurProject;
